#!/bin/bash
set -eux

export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

docker buildx create --use    --name builder node-amd64
docker buildx create --append --name builder node-arm64
docker buildx create --append --name builder node-ppc64le
docker buildx create --append --name builder node-s390x
docker buildx inspect --bootstrap
docker buildx ls
docker buildx build \
    --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
    --progress plain \
    $DOCKERFILE_PATH_ARG \
    -t $IMAGE_NAME \
    --push .
