#!/bin/bash
set -eu
export DOCKER_CLI_EXPERIMENTAL=enabled
export DOCKER_BUILDKIT=1
if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

docker buildx build \
    --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x \
    --progress plain --load \
    $DOCKERFILE_PATH_ARG \
    -t $IMAGE_NAME .
